minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  # Add packages to exclude from the minimum release age
  - "typescript@7.0.2"
  - "@typescript/*"
  - "oxlint@1.73.0"
  - "@oxlint/*"
trustPolicy: "no-downgrade"
preferFrozenLockfile: true
ignoreScripts: true
ignoreDepScripts: true
strictDepBuilds: true
engineStrict: false
ignorePnpmfile: true
blockExoticSubdeps: true
allowBuilds:
  # Add packages to allow running build scripts
  dprint: true
